server:
  port: 8000
store:
  type: postgres
  postgres:
    dsn: "postgres://admin:password@db:5432/terasprint?sslmode=disable"
llm:
  service: openai
memory:
  message_window: 12
extractors:
  messages:
    embeddings:
      service: openai
  documents:
    embeddings:
      service: openai
